import type { SignatureRule } from './types.js';

// Purposefully small, high-signal rules. Task 9 expands coverage after the core
// pipeline is live; ambiguous CSS classes and generic global names are avoided.
export const SIGNATURES: SignatureRule[] = [
  {
    name: 'WordPress',
    category: 'CMS',
    html: [/\/wp-content\//i, /\/wp-includes\//i],
    metaGenerator: /\bWordPress\b/i,
    ageRisk: 'aging',
    securityRisk: 'low',
  },
  {
    name: 'Drupal',
    category: 'CMS',
    html: [/\/sites\/(?:default|all)\/files\//i, /data-drupal-selector=/i],
    metaGenerator: /\bDrupal\b/i,
    ageRisk: 'aging',
    securityRisk: 'low',
  },
  {
    name: 'Joomla',
    category: 'CMS',
    html: [/\/media\/system\/js\//i, /option=com_[a-z0-9_]+/i],
    metaGenerator: /\bJoomla!?\b/i,
    ageRisk: 'aging',
    securityRisk: 'low',
  },
  {
    name: 'Shopify',
    category: 'Ecommerce',
    html: [/cdn\.shopify\.com/i, /Shopify\.theme/i],
    scriptSrc: [/cdn\.shopify\.com/i],
  },
  {
    name: 'Wix',
    category: 'Site Builder',
    html: [/static\.wixstatic\.com/i, /wix-code-sdk/i],
    metaGenerator: /\bWix\b/i,
  },
  {
    name: 'Squarespace',
    category: 'Site Builder',
    html: [/static\d*\.squarespace\.com/i, /Squarespace\.Commerce/i],
    metaGenerator: /\bSquarespace\b/i,
  },
  {
    name: 'React',
    category: 'JS Framework',
    html: [/data-reactroot(?:=|\s)/i, /__NEXT_DATA__/],
    scriptSrc: [/(?:^|[/.-])react(?:-dom)?(?:[.-]|\/)/i],
  },
  {
    name: 'Next.js',
    category: 'JS Framework',
    html: [/<script[^>]+id=["']__NEXT_DATA__["']/i, /\/_next\/static\//i],
    scriptSrc: [/\/_next\/static\//i],
  },
  {
    name: 'Vue.js',
    category: 'JS Framework',
    html: [/\bdata-v-[a-f0-9]{6,}\b/i, /id=["']__nuxt["']/i],
    scriptSrc: [/(?:^|[/.-])vue(?:\.runtime)?(?:\.min)?\.js(?:[?#]|$)/i],
  },
  {
    name: 'Nuxt',
    category: 'JS Framework',
    html: [/id=["']__nuxt["']/i, /\/_nuxt\//i],
    scriptSrc: [/\/_nuxt\//i],
  },
  {
    name: 'Angular',
    category: 'JS Framework',
    html: [/\bng-version=["'][^"']+["']/i, /<app-root(?:\s|>)/i],
    scriptSrc: [/(?:^|\/)angular(?:\.min)?\.js(?:[?#]|$)/i],
  },
  {
    name: 'Svelte',
    category: 'JS Framework',
    html: [/\bsvelte-[a-z0-9]+\b/i],
    scriptSrc: [/\/_app\/immutable\//i],
  },
  {
    name: 'jQuery',
    category: 'JS Library',
    scriptSrc: [/(?:^|[/.-])jquery(?:[-.]|\/)/i],
    ageRisk: 'aging',
    securityRisk: 'low',
  },
  {
    name: 'Bootstrap',
    category: 'UI Framework',
    html: [/(?:href|src)=["'][^"']*bootstrap(?:\.min)?\.(?:css|js)/i],
    scriptSrc: [/(?:^|[/.-])bootstrap(?:\.bundle)?(?:\.min)?\.js(?:[?#]|$)/i],
    ageRisk: 'aging',
  },
  {
    name: 'Tailwind CSS',
    category: 'UI Framework',
    html: [/cdn\.tailwindcss\.com/i],
    scriptSrc: [/cdn\.tailwindcss\.com/i],
  },
  {
    name: 'PHP',
    category: 'Language',
    headerKey: 'x-powered-by',
    headerValue: /\bPHP(?:\/|\b)/i,
    ageRisk: 'aging',
    securityRisk: 'low',
  },
  {
    name: 'Express',
    category: 'Web Framework',
    headerKey: 'x-powered-by',
    headerValue: /\bExpress\b/i,
    cookie: /^connect\.sid$/i,
    securityRisk: 'low',
  },
  {
    name: 'ASP.NET',
    category: 'Web Framework',
    headerKey: 'x-powered-by',
    headerValue: /\bASP\.NET\b/i,
    cookie: /^ASP\.NET_SessionId$/i,
    ageRisk: 'aging',
    securityRisk: 'low',
  },
  {
    name: 'Apache',
    category: 'Web Server',
    headerKey: 'server',
    headerValue: /\bApache(?:\/|\b)/i,
    ageRisk: 'aging',
    securityRisk: 'low',
  },
  {
    name: 'Nginx',
    category: 'Web Server',
    headerKey: 'server',
    headerValue: /\bnginx(?:\/|\b)/i,
  },
  {
    name: 'IIS',
    category: 'Web Server',
    headerKey: 'server',
    headerValue: /\bMicrosoft-IIS(?:\/|\b)/i,
    ageRisk: 'aging',
    securityRisk: 'low',
  },
  {
    name: 'Cloudflare',
    category: 'CDN',
    headerKey: 'server',
    headerValue: /\bcloudflare\b/i,
  },
  {
    name: 'Google Analytics',
    category: 'Analytics',
    html: [/googletagmanager\.com\/gtag\/js/i, /google-analytics\.com\/analytics\.js/i],
    scriptSrc: [
      /googletagmanager\.com\/gtag\/js/i,
      /google-analytics\.com\/analytics\.js/i,
    ],
  },
  {
    name: 'Google Tag Manager',
    category: 'Tag Manager',
    html: [/googletagmanager\.com\/gtm\.js/i, /GTM-[A-Z0-9]+/],
    scriptSrc: [/googletagmanager\.com\/gtm\.js/i],
  },
  {
    name: 'Hotjar',
    category: 'Analytics',
    html: [/static\.hotjar\.com\/c\/hotjar-/i],
    scriptSrc: [/static\.hotjar\.com\/c\/hotjar-/i],
    securityRisk: 'low',
  },
];
