import type { SignatureRule } from './types.js';

// Purposefully small, high-signal rules. Task 9 expands coverage after the core
// pipeline is live; ambiguous CSS classes and generic global names are avoided.
export const SIGNATURES: SignatureRule[] = [
  {
    name: 'WordPress',
    category: 'CMS',
    html: [/\/wp-content\//i, /\/wp-includes\//i],
    metaGenerator: /\bWordPress\b/i,
    ageRisk: 'aging',
    securityRisk: 'low',
  },
  {
    name: 'Drupal',
    category: 'CMS',
    html: [/\/sites\/(?:default|all)\/files\//i, /data-drupal-selector=/i],
    metaGenerator: /\bDrupal\b/i,
    ageRisk: 'aging',
    securityRisk: 'low',
  },
  {
    name: 'Joomla',
    category: 'CMS',
    html: [/\/media\/system\/js\//i, /option=com_[a-z0-9_]+/i],
    metaGenerator: /\bJoomla!?\b/i,
    ageRisk: 'aging',
    securityRisk: 'low',
  },
  {
    name: 'Shopify',
    category: 'Ecommerce',
    html: [/cdn\.shopify\.com/i, /Shopify\.theme/i],
    scriptSrc: [/cdn\.shopify\.com/i],
  },
  {
    name: 'Wix',
    category: 'Site Builder',
    html: [/static\.wixstatic\.com/i, /wix-code-sdk/i],
    metaGenerator: /\bWix\b/i,
  },
  {
    name: 'Squarespace',
    category: 'Site Builder',
    html: [/static\d*\.squarespace\.com/i, /Squarespace\.Commerce/i],
    metaGenerator: /\bSquarespace\b/i,
  },
  {
    name: 'React',
    category: 'JS Framework',
    html: [/data-reactroot(?:=|\s)/i, /__NEXT_DATA__/],
    scriptSrc: [/(?:^|[/.-])react(?:-dom)?(?:[.-]|\/)/i],
  },
  {
    name: 'Next.js',
    category: 'JS Framework',
    html: [/<script[^>]+id=["']__NEXT_DATA__["']/i, /\/_next\/static\//i],
    scriptSrc: [/\/_next\/static\//i],
  },
  {
    name: 'Vue.js',
    category: 'JS Framework',
    html: [/\bdata-v-[a-f0-9]{6,}\b/i, /id=["']__nuxt["']/i],
    scriptSrc: [/(?:^|[/.-])vue(?:\.runtime)?(?:\.min)?\.js(?:[?#]|$)/i],
  },
  {
    name: 'Nuxt',
    category: 'JS Framework',
    html: [/id=["']__nuxt["']/i, /\/_nuxt\//i],
    scriptSrc: [/\/_nuxt\//i],
  },
  {
    name: 'Angular',
    category: 'JS Framework',
    html: [/\bng-version=["'][^"']+["']/i, /<app-root(?:\s|>)/i],
    scriptSrc: [/(?:^|\/)angular(?:\.min)?\.js(?:[?#]|$)/i],
  },
  {
    name: 'Svelte',
    category: 'JS Framework',
    html: [/\bsvelte-[a-z0-9]+\b/i],
    scriptSrc: [/\/_app\/immutable\//i],
  },
  {
    name: 'jQuery',
    category: 'JS Library',
    scriptSrc: [/(?:^|[/.-])jquery(?:[-.]|\/)/i],
    ageRisk: 'aging',
    securityRisk: 'low',
  },
  {
    name: 'Bootstrap',
    category: 'UI Framework',
    html: [/(?:href|src)=["'][^"']*bootstrap(?:\.min)?\.(?:css|js)/i],
    scriptSrc: [/(?:^|[/.-])bootstrap(?:\.bundle)?(?:\.min)?\.js(?:[?#]|$)/i],
    ageRisk: 'aging',
  },
  {
    name: 'Tailwind CSS',
    category: 'UI Framework',
    html: [/cdn\.tailwindcss\.com/i],
    scriptSrc: [/cdn\.tailwindcss\.com/i],
  },
  {
    name: 'PHP',
    category: 'Language',
    headerKey: 'x-powered-by',
    headerValue: /\bPHP(?:\/|\b)/i,
    ageRisk: 'aging',
    securityRisk: 'low',
  },
  {
    name: 'Express',
    category: 'Web Framework',
    headerKey: 'x-powered-by',
    headerValue: /\bExpress\b/i,
    cookie: /^connect\.sid$/i,
    securityRisk: 'low',
  },
  {
    name: 'ASP.NET',
    category: 'Web Framework',
    headerKey: 'x-powered-by',
    headerValue: /\bASP\.NET\b/i,
    cookie: /^ASP\.NET_SessionId$/i,
    ageRisk: 'aging',
    securityRisk: 'low',
  },
  {
    name: 'Apache',
    category: 'Web Server',
    headerKey: 'server',
    headerValue: /\bApache(?:\/|\b)/i,
    ageRisk: 'aging',
    securityRisk: 'low',
  },
  {
    name: 'Nginx',
    category: 'Web Server',
    headerKey: 'server',
    headerValue: /\bnginx(?:\/|\b)/i,
  },
  {
    name: 'IIS',
    category: 'Web Server',
    headerKey: 'server',
    headerValue: /\bMicrosoft-IIS(?:\/|\b)/i,
    ageRisk: 'aging',
    securityRisk: 'low',
  },
  {
    name: 'Cloudflare',
    category: 'CDN',
    headerKey: 'server',
    headerValue: /\bcloudflare\b/i,
  },
  {
    name: 'Google Analytics',
    category: 'Analytics',
    html: [/googletagmanager\.com\/gtag\/js/i, /google-analytics\.com\/analytics\.js/i],
    scriptSrc: [
      /googletagmanager\.com\/gtag\/js/i,
      /google-analytics\.com\/analytics\.js/i,
    ],
  },
  {
    name: 'Google Tag Manager',
    category: 'Tag Manager',
    html: [/googletagmanager\.com\/gtm\.js/i, /GTM-[A-Z0-9]+/],
    scriptSrc: [/googletagmanager\.com\/gtm\.js/i],
  },
  {
    name: 'Hotjar',
    category: 'Analytics',
    html: [/static\.hotjar\.com\/c\/hotjar-/i],
    scriptSrc: [/static\.hotjar\.com\/c\/hotjar-/i],
    securityRisk: 'low',
  },
  {
    name: 'Ghost',
    category: 'CMS',
    html: [/\/ghost\/api\/content\//i, /cdn\.jsdelivr\.net\/ghost\//i],
    metaGenerator: /\bGhost\b/i,
  },
  {
    name: 'Webflow',
    category: 'Site Builder',
    html: [/\bdata-wf-page=["'][^"']+/i, /website-files\.com/i],
    metaGenerator: /\bWebflow\b/i,
  },
  {
    name: 'HubSpot CMS',
    category: 'CMS',
    html: [/js\.hs-scripts\.com/i, /hs_cos_wrapper/i],
    scriptSrc: [/js\.hs-scripts\.com/i],
  },
  {
    name: 'Contentful',
    category: 'Headless CMS',
    html: [/images\.ctfassets\.net/i, /cdn\.contentful\.com/i],
    scriptSrc: [/cdn\.contentful\.com/i],
  },
  {
    name: 'Sanity',
    category: 'Headless CMS',
    html: [/cdn\.sanity\.io\/images\//i],
    scriptSrc: [/cdn\.sanity\.io/i],
  },
  {
    name: 'DatoCMS',
    category: 'Headless CMS',
    html: [/datocms-assets\.com/i],
    scriptSrc: [/datocms-assets\.com/i],
  },
  {
    name: 'Strapi',
    category: 'Headless CMS',
    html: [/\/uploads\/[^"']+\.(?:webp|png|jpe?g)/i, /\bstrapi\b/i],
    headerKey: 'x-powered-by',
    headerValue: /\bStrapi\b/i,
  },
  {
    name: 'TYPO3',
    category: 'CMS',
    html: [/\/typo3temp\//i, /\/typo3conf\//i],
    metaGenerator: /\bTYPO3\b/i,
    ageRisk: 'aging',
    securityRisk: 'low',
  },
  {
    name: 'Umbraco',
    category: 'CMS',
    html: [/\/umbraco\/(?:api|surface)\//i],
    cookie: /^UMB-/i,
    ageRisk: 'aging',
    securityRisk: 'low',
  },
  {
    name: 'Blogger',
    category: 'CMS',
    html: [/blogger\.com\/static\//i, /\.blogspot\.com/i],
    metaGenerator: /\bBlogger\b/i,
    ageRisk: 'aging',
  },
  {
    name: 'Medium',
    category: 'Publishing',
    html: [/cdn-images-\d+\.medium\.com/i, /miro\.medium\.com/i],
  },
  {
    name: 'Magento',
    category: 'Ecommerce',
    html: [/\/static\/version\d+\/frontend\//i, /Magento_Ui\/js/i],
    cookie: /^(?:PHPSESSID|form_key)$/i,
    ageRisk: 'aging',
    securityRisk: 'low',
  },
  {
    name: 'WooCommerce',
    category: 'Ecommerce',
    html: [/\/plugins\/woocommerce\//i, /\bwoocommerce-(?:page|product)/i],
    cookie: /^woocommerce_/i,
    ageRisk: 'aging',
    securityRisk: 'low',
  },
  {
    name: 'BigCommerce',
    category: 'Ecommerce',
    html: [/cdn\d*\.bigcommerce\.com/i, /stencil-utils/i],
    scriptSrc: [/cdn\d*\.bigcommerce\.com/i],
  },
  {
    name: 'PrestaShop',
    category: 'Ecommerce',
    html: [/\/themes\/[^"']+\/assets\//i, /\bprestashop\b/i],
    metaGenerator: /\bPrestaShop\b/i,
    ageRisk: 'aging',
    securityRisk: 'low',
  },
  {
    name: 'Salesforce Commerce Cloud',
    category: 'Ecommerce',
    html: [/on\/demandware\.store\//i, /dwac_/i],
    cookie: /^dwsid$/i,
  },
  {
    name: 'Ecwid',
    category: 'Ecommerce',
    html: [/app\.ecwid\.com\/script\.js/i, /ec-storefront-v/i],
    scriptSrc: [/app\.ecwid\.com\/script\.js/i],
  },
  {
    name: 'Remix',
    category: 'JS Framework',
    html: [/__remixContext/i, /\/build\/_assets\//i],
    scriptSrc: [/\/build\/_assets\//i],
  },
  {
    name: 'Astro',
    category: 'JS Framework',
    html: [/\bastro-island\b/i, /data-astro-cid-/i],
    scriptSrc: [/\/_astro\//i],
  },
  {
    name: 'Gatsby',
    category: 'JS Framework',
    html: [/___gatsby/i, /webpack-runtime-[a-f0-9]+\.js/i],
    scriptSrc: [/\/page-data\/app-data\.json/i],
  },
  {
    name: 'Ember.js',
    category: 'JS Framework',
    html: [/\bember-view\b/i, /id=["']ember\d+["']/i],
    scriptSrc: [/(?:^|[/.-])ember(?:\.min)?\.js/i],
    ageRisk: 'aging',
  },
  {
    name: 'Alpine.js',
    category: 'JS Framework',
    html: [/\bx-data(?:=|\s)/i, /\bx-init(?:=|\s)/i],
    scriptSrc: [/(?:^|[/.-])alpinejs(?:[.@/-]|$)/i],
  },
  {
    name: 'htmx',
    category: 'JS Library',
    html: [/\bhx-(?:get|post|put|delete|swap|target)=/i],
    scriptSrc: [/(?:^|[/.-])htmx(?:\.min)?\.js/i],
  },
  {
    name: 'Preact',
    category: 'JS Framework',
    scriptSrc: [/(?:^|[/.-])preact(?:[.@/-]|$)/i],
  },
  {
    name: 'SolidJS',
    category: 'JS Framework',
    scriptSrc: [/(?:^|[/.-])solid-js(?:[.@/-]|$)/i],
  },
  {
    name: 'Lit',
    category: 'Web Components',
    scriptSrc: [/(?:^|[/.-])lit-element(?:[.@/-]|$)/i, /@lit\/reactive-element/i],
  },
  {
    name: 'Stimulus',
    category: 'JS Framework',
    html: [/\bdata-controller=["'][^"']+/i, /\bdata-action=["'][^"']+->/i],
    scriptSrc: [/@hotwired\/stimulus/i],
  },
  {
    name: 'Turbo',
    category: 'JS Framework',
    html: [/\bdata-turbo-(?:method|frame|action)=/i],
    scriptSrc: [/@hotwired\/turbo/i],
  },
  {
    name: 'Backbone.js',
    category: 'JS Framework',
    scriptSrc: [/(?:^|[/.-])backbone(?:\.min)?\.js/i],
    ageRisk: 'eol',
    securityRisk: 'low',
  },
  {
    name: 'Knockout.js',
    category: 'JS Framework',
    html: [/\bdata-bind=["'][^"']+/i],
    scriptSrc: [/(?:^|[/.-])knockout(?:\.min)?\.js/i],
    ageRisk: 'aging',
  },
  {
    name: 'MooTools',
    category: 'JS Library',
    scriptSrc: [/(?:^|[/.-])mootools(?:-core)?(?:\.min)?\.js/i],
    ageRisk: 'eol',
    securityRisk: 'low',
  },
  {
    name: 'RequireJS',
    category: 'JS Loader',
    html: [/\bdata-main=["'][^"']+/i],
    scriptSrc: [/(?:^|[/.-])require(?:\.min)?\.js/i],
    ageRisk: 'aging',
  },
  {
    name: 'Laravel',
    category: 'Web Framework',
    headerKey: 'x-powered-by',
    headerValue: /\bLaravel\b/i,
    cookie: /^(?:laravel_session|XSRF-TOKEN)$/i,
    securityRisk: 'low',
  },
  {
    name: 'Ruby on Rails',
    category: 'Web Framework',
    headerKey: 'x-powered-by',
    headerValue: /\bPhusion Passenger\b/i,
    cookie: /^_.*_session$/i,
    securityRisk: 'low',
  },
  {
    name: 'Django',
    category: 'Web Framework',
    cookie: /^(?:csrftoken|django_language)$/i,
  },
  {
    name: 'Flask',
    category: 'Web Framework',
    headerKey: 'server',
    headerValue: /\bWerkzeug\//i,
  },
  {
    name: 'Spring',
    category: 'Web Framework',
    cookie: /^JSESSIONID$/i,
    headerKey: 'x-application-context',
    headerValue: /.+/,
    securityRisk: 'low',
  },
  {
    name: 'FastAPI',
    category: 'Web Framework',
    headerKey: 'server',
    headerValue: /\buvicorn\b/i,
  },
  {
    name: 'Phoenix',
    category: 'Web Framework',
    headerKey: 'x-powered-by',
    headerValue: /\bPhoenix\b/i,
    cookie: /^_.*_key$/i,
  },
  {
    name: 'CakePHP',
    category: 'Web Framework',
    cookie: /^CAKEPHP$/i,
    ageRisk: 'aging',
    securityRisk: 'low',
  },
  {
    name: 'Symfony',
    category: 'Web Framework',
    headerKey: 'x-debug-token',
    headerValue: /.+/,
    cookie: /^sf_redirect$/i,
  },
  {
    name: 'CodeIgniter',
    category: 'Web Framework',
    cookie: /^ci_session$/i,
    ageRisk: 'aging',
    securityRisk: 'low',
  },
  {
    name: 'Caddy',
    category: 'Web Server',
    headerKey: 'server',
    headerValue: /\bCaddy\b/i,
  },
  {
    name: 'LiteSpeed',
    category: 'Web Server',
    headerKey: 'server',
    headerValue: /\bLiteSpeed\b/i,
    ageRisk: 'aging',
  },
  {
    name: 'OpenResty',
    category: 'Web Server',
    headerKey: 'server',
    headerValue: /\bopenresty\b/i,
  },
  {
    name: 'Apache Tomcat',
    category: 'Application Server',
    headerKey: 'server',
    headerValue: /\bApache-Coyote\b|\bTomcat\b/i,
    ageRisk: 'aging',
    securityRisk: 'low',
  },
  {
    name: 'Vercel',
    category: 'Hosting',
    headerKey: 'server',
    headerValue: /\bVercel\b/i,
    html: [/\.vercel-insights\.com/i],
  },
  {
    name: 'Netlify',
    category: 'Hosting',
    headerKey: 'server',
    headerValue: /\bNetlify\b/i,
    html: [/data-netlify(?:=|\s)/i],
  },
  {
    name: 'AWS CloudFront',
    category: 'CDN',
    headerKey: 'via',
    headerValue: /\bCloudFront\b/i,
  },
  {
    name: 'Fastly',
    category: 'CDN',
    headerKey: 'x-served-by',
    headerValue: /\bcache-[a-z0-9-]+-Fastly\b/i,
  },
  {
    name: 'Akamai',
    category: 'CDN',
    headerKey: 'server',
    headerValue: /\bAkamaiGHost\b/i,
  },
  {
    name: 'Firebase Hosting',
    category: 'Hosting',
    headerKey: 'server',
    headerValue: /\bGoogle Frontend\b/i,
    html: [/firebaseapp\.com/i],
  },
  {
    name: 'GitHub Pages',
    category: 'Hosting',
    headerKey: 'server',
    headerValue: /\bGitHub\.com\b/i,
    html: [/github\.io/i],
  },
  {
    name: 'Render',
    category: 'Hosting',
    headerKey: 'server',
    headerValue: /\bRender\b/i,
    html: [/\.onrender\.com/i],
  },
  {
    name: 'Fly.io',
    category: 'Hosting',
    headerKey: 'server',
    headerValue: /\bFly\b/i,
    html: [/\.fly\.dev/i],
  },
  {
    name: 'Plausible Analytics',
    category: 'Analytics',
    scriptSrc: [/plausible\.io\/js\/script/i],
  },
  {
    name: 'Matomo',
    category: 'Analytics',
    html: [/\b_matomo\.push\b/i, /\b_paq\.push\b/i],
    scriptSrc: [/(?:matomo|piwik)\.js/i],
  },
  {
    name: 'Mixpanel',
    category: 'Analytics',
    html: [/cdn\.mxpnl\.com\/libs\/mixpanel/i],
    scriptSrc: [/cdn\.mxpnl\.com\/libs\/mixpanel/i],
  },
  {
    name: 'Segment',
    category: 'Analytics',
    html: [/cdn\.segment\.com\/analytics\.js/i],
    scriptSrc: [/cdn\.segment\.com\/analytics\.js/i],
  },
  {
    name: 'Amplitude',
    category: 'Analytics',
    scriptSrc: [/cdn\.amplitude\.com\/libs\//i],
  },
  {
    name: 'Heap',
    category: 'Analytics',
    html: [/cdn\.heapanalytics\.com\/js\/heap-/i],
    scriptSrc: [/cdn\.heapanalytics\.com\/js\/heap-/i],
  },
  {
    name: 'Fathom Analytics',
    category: 'Analytics',
    scriptSrc: [/cdn\.usefathom\.com\/script\.js/i],
  },
  {
    name: 'Microsoft Clarity',
    category: 'Analytics',
    html: [/clarity\.ms\/tag\//i],
    scriptSrc: [/clarity\.ms\/tag\//i],
  },
  {
    name: 'Sentry',
    category: 'Monitoring',
    html: [/browser\.sentry-cdn\.com/i],
    scriptSrc: [/browser\.sentry-cdn\.com/i, /@sentry\/browser/i],
  },
  {
    name: 'New Relic',
    category: 'Monitoring',
    html: [/js-agent\.newrelic\.com/i],
    scriptSrc: [/js-agent\.newrelic\.com/i],
  },
  {
    name: 'Datadog RUM',
    category: 'Monitoring',
    scriptSrc: [/datadoghq-browser-agent\.com/i, /@datadog\/browser-rum/i],
  },
  {
    name: 'Bugsnag',
    category: 'Monitoring',
    scriptSrc: [/d2wy8f7a9ursnm\.cloudfront\.net\/bugsnag/i, /@bugsnag\/js/i],
  },
  {
    name: 'Rollbar',
    category: 'Monitoring',
    html: [/cdn\.rollbar\.com\/rollbarjs/i],
    scriptSrc: [/cdn\.rollbar\.com\/rollbarjs/i],
  },
  {
    name: 'Intercom',
    category: 'Customer Support',
    html: [/widget\.intercom\.io\/widget\//i],
    scriptSrc: [/widget\.intercom\.io\/widget\//i],
  },
  {
    name: 'HubSpot',
    category: 'Marketing',
    html: [/js\.hs-analytics\.net/i, /js\.hsforms\.net/i],
    scriptSrc: [/js\.hs-(?:analytics|forms)\.net/i],
  },
  {
    name: 'Marketo',
    category: 'Marketing',
    html: [/munchkin\.marketo\.net\/munchkin\.js/i],
    scriptSrc: [/munchkin\.marketo\.net\/munchkin\.js/i],
  },
  {
    name: 'Mailchimp',
    category: 'Marketing',
    html: [/chimpstatic\.com\/mcjs-connected/i, /list-manage\.com\/subscribe/i],
    scriptSrc: [/chimpstatic\.com\/mcjs-connected/i],
  },
  {
    name: 'Klaviyo',
    category: 'Marketing',
    scriptSrc: [/static\.klaviyo\.com\/onsite\/js/i],
  },
  {
    name: 'Drift',
    category: 'Customer Support',
    scriptSrc: [/js\.driftt\.com\/include\//i],
  },
  {
    name: 'Zendesk',
    category: 'Customer Support',
    html: [/static\.zdassets\.com\/ekr\/snippet\.js/i],
    scriptSrc: [/static\.zdassets\.com\/ekr\/snippet\.js/i],
  },
  {
    name: 'Stripe',
    category: 'Payments',
    html: [/js\.stripe\.com\/v3\//i],
    scriptSrc: [/js\.stripe\.com\/v3\//i],
  },
  {
    name: 'PayPal',
    category: 'Payments',
    html: [/paypal\.com\/sdk\/js/i, /paypalobjects\.com\/api\/checkout/i],
    scriptSrc: [/paypal\.com\/sdk\/js/i, /paypalobjects\.com\/api\/checkout/i],
  },
  {
    name: 'Braintree',
    category: 'Payments',
    scriptSrc: [/js\.braintreegateway\.com\/web\//i],
  },
  {
    name: 'Adyen',
    category: 'Payments',
    scriptSrc: [/checkoutshopper-(?:live|test)\.adyen\.com/i],
  },
  {
    name: 'Square',
    category: 'Payments',
    scriptSrc: [/web\.squarecdn\.com\/v1\/square\.js/i],
  },
  {
    name: 'Klarna',
    category: 'Payments',
    scriptSrc: [/x\.klarnacdn\.net\/klarna\.js/i],
  },
  {
    name: 'Cloudinary',
    category: 'Media CDN',
    html: [/res\.cloudinary\.com\/[^/]+\/image\/upload/i],
  },
  {
    name: 'Imgix',
    category: 'Media CDN',
    html: [/\.imgix\.net\/[^"']+\?(?:[^"']*&)?(?:w|h|fit)=/i],
  },
  {
    name: 'jsDelivr',
    category: 'CDN',
    html: [/cdn\.jsdelivr\.net\/(?:npm|gh)\//i],
    scriptSrc: [/cdn\.jsdelivr\.net\/(?:npm|gh)\//i],
  },
  {
    name: 'unpkg',
    category: 'CDN',
    html: [/unpkg\.com\/[^"']+/i],
    scriptSrc: [/unpkg\.com\/[^"']+/i],
  },
  {
    name: 'Google reCAPTCHA',
    category: 'Security',
    html: [/google\.com\/recaptcha\/api\.js/i, /\bg-recaptcha\b/i],
    scriptSrc: [/google\.com\/recaptcha\/api\.js/i],
  },
  {
    name: 'hCaptcha',
    category: 'Security',
    html: [/js\.hcaptcha\.com\/1\/api\.js/i, /\bh-captcha\b/i],
    scriptSrc: [/js\.hcaptcha\.com\/1\/api\.js/i],
  },
  {
    name: 'Cloudflare Turnstile',
    category: 'Security',
    html: [/challenges\.cloudflare\.com\/turnstile\/v0\/api\.js/i, /\bcf-turnstile\b/i],
    scriptSrc: [/challenges\.cloudflare\.com\/turnstile\/v0\/api\.js/i],
  },
  {
    name: 'OneTrust',
    category: 'Consent Management',
    html: [/cdn\.cookielaw\.org\/scripttemplates\/otSDKStub\.js/i],
    scriptSrc: [/cdn\.cookielaw\.org\/scripttemplates\/otSDKStub\.js/i],
  },
  {
    name: 'Cookiebot',
    category: 'Consent Management',
    html: [/consent\.cookiebot\.com\/uc\.js/i],
    scriptSrc: [/consent\.cookiebot\.com\/uc\.js/i],
  },
  {
    name: 'Google Fonts',
    category: 'Web Font',
    html: [/fonts\.googleapis\.com\/css2?/i],
  },
  {
    name: 'Font Awesome',
    category: 'Icon Library',
    html: [/(?:use\.fontawesome\.com|kit\.fontawesome\.com|font-awesome(?:\.min)?\.css)/i],
    scriptSrc: [/kit\.fontawesome\.com\/[a-z0-9]+\.js/i],
  },
  {
    name: 'Algolia',
    category: 'Search',
    html: [/cdn\.jsdelivr\.net\/npm\/algoliasearch/i, /algolianet\.com/i],
    scriptSrc: [/algoliasearch(?:-lite)?(?:\.min)?\.js/i],
  },
  {
    name: 'Vite',
    category: 'Build Tool',
    html: [/\/@vite\/client/i],
    scriptSrc: [/\/@vite\/client/i],
  },
  {
    name: 'webpack',
    category: 'Build Tool',
    html: [/webpackJsonp|webpackChunk[a-zA-Z0-9_]+/],
    scriptSrc: [/webpack-runtime(?:[.-][a-f0-9]+)?\.js/i],
  },
];
